// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd6CWJLN__xASlFHo6aNQVGghjGaQqg0c',
    appId: '1:523262104471:android:cd1cf27fe02259302eead2',
    messagingSenderId: '523262104471',
    projectId: 'karbon2-c39e7',
    storageBucket: 'karbon2-c39e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJofoTHi1wOdulPmW0ZQxdr3O8nOEAdHI',
    appId: '1:523262104471:ios:349f07eb68af53d82eead2',
    messagingSenderId: '523262104471',
    projectId: 'karbon2-c39e7',
    storageBucket: 'karbon2-c39e7.firebasestorage.app',
    iosBundleId: 'com.example.karbonson',
  );
  
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd6CWJLN__xASlFHo6aNQVGghjGaQqg0c',
    appId: '1:523262104471:web:cd1cf27fe02259302eead2',
    messagingSenderId: '523262104471',
    projectId: 'karbon2-c39e7',
    storageBucket: 'karbon2-c39e7.firebasestorage.app',
  );
  }