// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' as firebase_core;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static firebase_core.FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final firebase_core.FirebaseOptions web = firebase_core.FirebaseOptions(
    apiKey: 'AIzaSyCVlcHBwMjQ6cQSTXlvHNwEAZEhlVdHV20',
    appId: '1:523262104471:web:b0845c7efb193f712eead2',
    messagingSenderId: '523262104471',
    projectId: 'karbon2-c39e7',
    authDomain: 'karbon2-c39e7.firebaseapp.com',
    storageBucket: 'karbon2-c39e7.appspot.com',
    measurementId: 'G-KS0BHVZPQ3',
  );

  static final firebase_core.FirebaseOptions android = firebase_core.FirebaseOptions(
    apiKey: 'AIzaSyDd6CWJLN__xASlFHo6aNQVGghjGaQqg0c',
    appId: '1:523262104471:android:cd1cf27fe02259302eead2',
    messagingSenderId: '523262104471',
    projectId: 'karbon2-c39e7',
    storageBucket: 'karbon2-c39e7.appspot.com',
  );

  static final firebase_core.FirebaseOptions ios = firebase_core.FirebaseOptions(
    apiKey: 'AIzaSyAJofoTHi1wOdulPmW0ZQxdr3O8nOEAdHI',
    appId: '1:523262104471:ios:349f07eb68af53d82eead2',
    messagingSenderId: '523262104471',
    projectId: 'karbon2-c39e7',
    storageBucket: 'karbon2-c39e7.appspot.com',
    iosBundleId: 'com.example.karbonson',
  );

  static final firebase_core.FirebaseOptions macos = firebase_core.FirebaseOptions(
    apiKey: 'AIzaSyAJofoTHi1wOdulPmW0ZQxdr3O8nOEAdHI',
    appId: '1:523262104471:ios:349f07eb68af53d82eead2',
    messagingSenderId: '523262104471',
    projectId: 'karbon2-c39e7',
    storageBucket: 'karbon2-c39e7.appspot.com',
    iosBundleId: 'com.example.karbonson',
  );

  static final firebase_core.FirebaseOptions windows = firebase_core.FirebaseOptions(
    apiKey: 'AIzaSyCVlcHBwMjQ6cQSTXlvHNwEAZEhlVdHV20',
    appId: '1:523262104471:web:30bce558b6f3094a2eead2',
    messagingSenderId: '523262104471',
    projectId: 'karbon2-c39e7',
    authDomain: 'karbon2-c39e7.firebaseapp.com',
    storageBucket: 'karbon2-c39e7.appspot.com',
    measurementId: 'G-08WE3MPZ5Y',
  );

}