# platform minimumunu projenize göre yükseltebilirsiniz (ör. '12.0' veya '13.0')
platform :ios, '11.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

flutter_root = File.expand_path(File.join(__dir__, '..', 'Development', 'flutter'))
# Eğer yukarıdaki yol yanlışsa flutter_root'u aşağıdaki gibi otomatik bulmaya değiştir:
# flutter_root = File.expand_path(File.join(__dir__, '..', '.'))

# Flutter'ın podhelper'ını yükle
load File.join(File.expand_path('..', __dir__), 'flutter', 'packages', 'flutter_tools', 'bin', 'podhelper.rb') rescue load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end